name: 📄 Build docs

on:
    pull_request:
    push:
        branches: ["main", "develop", "release"]

env:
    CARGO_TERM_COLOR: always

jobs:
    docs:
        name: 📄 Build docs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build docs
              run: cargo doc --verbose
