{% raw %}
name: 👔 Check formatting

on:
    pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
    check_format:
        name: 👔 Check formatting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install latest ${{ matrix.toolchain }}
              uses: actions-rs/toolchain@v1
              with:
                toolchain: ${{ matrix.toolchain }}
            - uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
            - name: Check Formatting
              run: cargo fmt -- --check --color auto
{% endraw %}