{% raw %}
name: 🚀 Release

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: 🚀 Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install latest stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Semantic Release
# The semantic release also runs 'poetry build' this is configured in the config.js file
        run: |
          npm -g install @semantic-release/git semantic-release semantic-release-github-actions-tags @semantic-release/changelog @semantic-release/github @semantic-release/exec
          npx semantic-release
#      - name: Here you can add your publishing command
#        run: poetry publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

{% endraw %}